name: fluttertodolistsqfliteapp
description: A new Flutter todolist sqflite application.



environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  graphql: ^4.0.0-beta
  path_provider: ^1.6.7
  intl: ^0.16.1

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter




# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
